name: Android CI

# 参考：https://qiita.com/uhooi/items/70ffe67ba65d33189db2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      # Gradleのキャッシュ復元：https://github.com/actions/cache/blob/main/examples.md#java---gradle
#      - uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      # 依存関係の出力
#      - name: Displays the Android dependencies of the project
#        run: ./gradlew androidDependencies
#
#      # コンパイル
#      - name: Run Compile
#        run: ./gradlew assembleDebug

  test:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v3

      # JDKのセットアップ
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # テスト
      # https://speakerdeck.com/hkusu/github-actions-deyunitutotesutofalsejie-guo-worepotosuru?slide=7
      - name: Test with Gradle
        run: ./gradlew testDebugUnitTest

      # https://github.com/mikepenz/action-junit-report
      - if: always()
        name: Publish test report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: ./**/junit-reports/

      - name: Publish test reports
        if: always()
        uses: mikepenz/action-junit-report@v3.1.0
        with:
          check_name: test-report
          report_paths: '**/junit-reports/TEST-*.xml'
          fail_on_failure: 'true'

  # https://github.com/DVDAndroid/action-android-lint
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle build
        run: ./gradlew build

      - name: Run Android Lint
        uses: dvdandroid/action-android-lint@master
        with:
          github_token: ${{ secrets.github_token }}
          lint_xml_file: app/build/reports/lint-results.xml

  # https://github.com/ScaCap/action-ktlint
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter
