name: Android CI

# 参考：https://qiita.com/uhooi/items/70ffe67ba65d33189db2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradleのキャッシュ復元：https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 依存関係の出力
      - name: Displays the Android dependencies of the project
        run: ./gradlew androidDependencies

      # コンパイル
      - name: Run Compile
        run: ./gradlew assembleDebug

  test:
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v3

      # JDKのセットアップ
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradleのキャッシュ復元
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # テスト
      - name: Test with Gradle
        run: ./gradlew test

      # https://github.com/mikepenz/action-junit-report
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
